### ISSUE TITLE
Дублирование полей в пакете для валидации

### ISSUE THREAD

**Issue by Prots** [koorchik/LIVR#18]
Не понятно какое из полей валидатор пропускает и почему не выдает оба в резалтсете:
http://webbylab.github.io/livr-playground/#{%22rules%22%3A%22{\n%20%20%20%20name%3A%20%27required%27%2C\n%20%20%20%20email%3A%20[%27required%27%2C%20%27email%27]%2C\n%20%20%20%20gender%3A%20{%20one_of%3A%20[[%27male%27%2C%20%27female%27]]%20}%2C\n%20%20%20%20phone%3A%20{max_length%3A%2010}%2C\n%20%20%20%20password%3A%20[%27required%27%2C%20{min_length%3A%2010}%20]%2C\n%20%20%20%20password2%3A%20{%20equal_to_field%3A%20%27password%27%20}\n}%22%2C%22data%22%3A%22{\n%20%20%20%20name%3A%20%27John%27%2C\n%20%20%20%20email%3A%20%27john%40mail1.com%27%2C\n%20%20%20%20email%3A%20%27john%40mail.com%27%2C\n%20%20%20%20gender%3A%20%27male%27%2C\n%20%20%20%20gender%3A%20%27male%27%2C\n%20%20%20%20phone%3A%20%27%2B22221212%27%2C\n%20%20%20%20password%3A%20%27mypassword1%27%2C\n%20%20%20%20password2%3A%20%27mypassword1%27\n}%22}

**Comment by SDSWanderer** [comment]
Не баг. Это естественное поведение при работе с именованным массивом (объектом в JS), и никак не относится ни к спецификации LIVR ни к JS реализации. JS реализация LIVR принимает и возвращает объекты. В объекте не может быть не уникальных ключей. Метод `validate()` принимает объект, и в нем уже нет не уникальных ключей. Объект с не уникальными ключами можно описать как строку JSON, но при парсинге не уникальные ключи будут потеряны. Какие именно - зависит от реализации `JSON.parse`. 
Подозреваю что в erlang туплы имеют другое поведение, если это так - эту проблему нужно решить в erlang реализации, но не на уровне спецификации LIVR и не в JS реализации.

**Comment by koorchik** [comment]
В хештаблице не может быть 2 одинаковых ключа. Когда создается объект в нем будет один ключ и LIVR уже принимает объект с одним ключем.

Попробуйте:
```
console.log({
    name: 'John',
    email: 'john@mail1.com',
    email: 'john@mail.com',
    gender: 'male',
    gender: 'male',
    phone: '+22221212',
    password: 'mypassword1',
    password2: 'mypassword1'
})
```
или 
```
JSON.stringify({
    name: 'John',
    email: 'john@mail1.com',
    email: 'john@mail.com',
    gender: 'male',
    gender: 'male',
    phone: '+22221212',
    password: 'mypassword1',
    password2: 'mypassword1'
})
```

**Comment by Prots** [comment]
Как раз в спецификации и должно быть указано поведение на случай обнаружения двух одинаковых полей,  иначе для разных реализаций будет разное поеведение.

**Comment by koorchik** [comment]
LIVR не может повлиять на это, поскольку он не видит двух ключей. Хештаблица не может содержать два одинаковых ключа. Вся идея хеш-таблицы в том, ключ - это идентификатор для доступак значению.

**Comment by SDSWanderer** [comment]
@Prots я правильно понял что в Erlang есть некая специфичная структура данных в которой возможны не уникальные ключи? Можно пример кода по ее созданию и перечислению ключей\значений, так чтоб было видно что каждому ключу соответствует свое значение + есть два одинаковых ключа.  
Для всех остальных реализаций (Perl, JS, PHP, Python) эта проблема не актуальна, так как в этих языках нельзя создать структуру данных с одинаковыми ключами.

**Comment by Prots** [comment]
В erlang maps появились относительно недавно, в 17-й версии, и еще не полностью обкатаны, поэтому в либе используется proplists, а он позволяет хранить что угодно и не накладывает ограничений. 
Надо подумать и возможно перейти на мапы в erlang реализации LIVR.

**Comment by SDSWanderer** [comment]
Интересно. В таком случае предлагаю до тех пор пока используются proplists обрабатывать последнее (или первое, что проще) описанное значение, остальные вырезать. Ну и явно описать эту проблему в спецификации Erlang реализации.

**Comment by SDSWanderer** [comment]
Ну или сопоставлять ключи и данные по порядку:  N'ный ключ в правилах соответствует N'ному ключу во входных данных, раз уж для описания правил валидации тоже используются proplists.
