### ISSUE TITLE
Добавить плагин к Mojolicious

### ISSUE THREAD

**Issue by thefree** [koorchik/LIVR#2]
у Вас есть http://koorchik.blogspot.ru/2012/01/mojolicious.html , пользовался.
Логично увидеть и для LIVR

**Comment by koorchik** [comment]
Currently there is no Mojo plugin. We switched from rendering HTML on a server to providing REST APIs. So, we use Validator::LIVR directly (without Mojolicious helpers). It is a great idea to port Mojolicious::Plugin::ValidateTiny to LIVR, but it should be done by person who will be using the plugin in real project. Currently we are not going to switch back to rendering HTML on a server, closing the issue for now.
