### ISSUE TITLE
Shorthand for "nested_object"

### ISSUE THREAD

**Issue by SDSWanderer** [koorchik/LIVR#21]
Можно упростить описание вложенных объектов, если при парсинге правил интерпретировать хеш как вызов правила `nested_object`.

Т.е вместо 
```javascript
var rules = {
    address: {nested_object: {
        city: 'required',
        zip: ['required', 'positive_integer']
    }}
}
```
Позволить писать
```javascript
var rules = {
    address: {
        city: 'required',
        zip: ['required', 'positive_integer']
    }
}
```
 Это довольно очевидное, однозначное и удобное сокращение, ведь поля на верхнем уровне (`address`) мы *не* оборачиваем в `nested_object` так:

```javascript
var rules = {nested_object: {
    address: {nested_object: {
        city: 'required',
        zip: ['required', 'positive_integer']
    }}
}}
```

**Comment by koorchik** [comment]
как отличить

```
address: {min_length: 10}
```
и
```
address: { city: 'required' }
```
min_length - правило, city - поле

**Comment by koorchik** [comment]
сакратить можно nested_object переименовав в object, или в  dict, hash, map

**Comment by SDSWanderer** [comment]
Да, плохая идея. Надежно определить не выйдет. Переименовывать, имхо, не стОит, меня лично больше утомляют излишние скобки.
