### ISSUE TITLE
Разработать концепцию Language Independent типизации

### ISSUE THREAD

**Issue by SDSWanderer** [koorchik/LIVR#22]
Исторически сложилось так, что первая реализация LIVR была написана на Perl, и LIVR во многом унаследовал его систему типов, а именно:

* Нет разницы между строкой и числом
* Нет логического типа (true, false)

Это приводит к шоку разработчиков, которые не ожидают, например что правило ["positive_integer" пропустит строку "1"](http://livr-playground.tk/#%7B%22rules%22%3A%22%7B%5Cn%20%20flag%3A%20%7Bone_of%3A%20%5Btrue%2C%20false%5D%7D%2C%5Cn%20%20amount%3A%20%5C%22positive_integer%5C%22%5Cn%7D%22%2C%22input%22%3A%22%7B%5Cn%20%20flag%3A%20true%2C%5Cn%20%20amount%3A%20%5C%221%5C%22%5Cn%7D%22%7D).

Нужно выработать универсальную концепцию для стандартных правил (и расширить набор тестов), и предложить best practices для пользователей реализаций, так как они работают с конкретным языком, и должны позаботиться о типах. 
 
Еще пара кейсов:
* [{ flag: {one_of: [true, false]} }](http://livr-playground.tk/#%7B%22rules%22%3A%22%7B%20flag%3A%20%7Bone_of%3A%20%5Btrue%2C%20false%5D%7D%20%7D%22%2C%22input%22%3A%22%7B%5Cn%20%20flag%3A%20true%2C%5Cn%7D%22%7D)
* [{ flag: {one_of: 4} }](http://livr-playground.tk/#%7B%22rules%22%3A%22%7B%20flag%3A%20%7Bone_of%3A%204%7D%20%7D%22%2C%22input%22%3A%22%7B%5Cn%20%20flag%3A%204%5Cn%7D%22%7D)

**Comment by koorchik** [comment]
Обсуждения начато тут #11
