### ISSUE TITLE
Округление float'ов

### ISSUE THREAD

**Issue by SDSWanderer** [koorchik/LIVR#23]
Один из кейсов который приводит к не одинаковому поведению. Не уверен что это баг, но возможно стоит упомянуть об этом в спецификации:

[{ flag: {one_of: 4.00000000000001} }](http://livr-playground.tk/#%7B%22rules%22%3A%22%7B%20flag%3A%20%7Bone_of%3A%204.00000000000001%7D%20%7D%22%2C%22input%22%3A%22%7B%5Cn%20%20flag%3A%204%5Cn%7D%22%7D) - PHP сдался
[{ flag: {one_of: 4.000000000000001} }](http://livr-playground.tk/#%7B%22rules%22%3A%22%7B%20flag%3A%20%7Bone_of%3A%204.000000000000001%7D%20%7D%22%2C%22input%22%3A%22%7B%5Cn%20%20flag%3A%204%5Cn%7D%22%7D) - Perl тоже
[{ flag: {one_of: 4.0000000000000001} }](http://livr-playground.tk/#%7B%22rules%22%3A%22%7B%20flag%3A%20%7Bone_of%3A%204.0000000000000001%7D%20%7D%22%2C%22input%22%3A%22%7B%5Cn%20%20flag%3A%204%5Cn%7D%22%7D) - JavaScript и Python
\* а в erlng вообще не так, но это уже кейс для #22

**Comment by koorchik** [comment]
По идее должно быть решено в новой версии спеки. Вот как будет работать:
And one issue is equality. Should it be strict or not? And should we do any type coercing of result? For example, for "one_of" or "eq" rules. We cannot do fully relaxed comparison as it can work differently in different languages. So, it should work as the following:

1. The rules are **string rules**. So, we should compare values as strings. Before comparing we should coerce them to strings (if it required by language to compare)
2. The rule should return what user expects. So, if we have input

    {
        field1: 1,
        field2: "1"
    }

and rules:

    {
        field1: {one_of: "1"},
        field2: {one_of: 1},
    }

then the result will be

    {
        field1: "1",
        field2: 1
    }
