### ISSUE TITLE
Allow empty validation for a field

### ISSUE THREAD

**Issue by amakhrov** [koorchik/LIVR#24]
My form allows arbitrary string value for one of the fields. And this field is optional (not required).
How can I configure a LIVR rule for that?
I tried to pass `'fieldName' => NULL` and `'fieldName' => []` - both trigger an error after calling `validate()`:
`Exception: Rule [] not registered`
and
`Undefined index:`

**Comment by koorchik** [comment]
Pass any rule. For example min_length

http://webbylab.github.io/livr-playground/#%7B%22rules%22%3A%22%7B%5Cn%20%20%20%20name%3A%20%7B%20min_length%3A%201%20%7D%5Cn%7D%22%2C%22data%22%3A%22%7B%5Cn%20%20%20%20name%3A%20'John'%5Cn%7D%22%7D

**Comment by koorchik** [comment]
We want to add new rule "any" in future versions of LIVR

**Comment by amakhrov** [comment]
Thanks. Passing any rule probably works as a temporary workaround - but it kind breaks the semantics.
Why not allow an empty list of validations (`[]`) for such cases?

**Comment by koorchik** [comment]
I am going to update the spec (not sure will it be empty array or "any" rule) but I am not sure that the update matches your need. 
For example, if you say {fieldName: []} it means that user can pass string or array or hash. But in most cases developers want any string but not array or hash. Can you describe your case?

**Comment by amakhrov** [comment]
@koorchik you're right, in my case it should be an arbitrary string (even a missing field) - but not e.g. an array.

**Comment by Sandvich** [comment]
Hi, similar issue here. I need a field that can never fail validation. Any thoughts on how to do that?
The default value is an empty string, but there's potential for other things to be stored in there too.

**Comment by SDSWanderer** [comment]
@Sandvich, lock at the discussion above, answer is here.

**Comment by Sandvich** [comment]
@SDSWanderer Yeah, I'm currently using min_length as suggested. That crashes when you try and put an integer in there, however, as integers have no length (at least not in python).

**Comment by SDSWanderer** [comment]
@Sandvich, ok, you can register you own rule (`any` for example). Rule implementation is trivial, just always return empty function.

**Comment by Sandvich** [comment]
Great, thanks!

**Comment by koorchik** [comment]
"string" rule will be added to the LIVR 2.0 instead of "any". Will match any string.
