### ISSUE TITLE
Release v2.0

### ISSUE THREAD

**Issue by koorchik** [koorchik/LIVR#27]
This issue is for discussion of the features that should be covered by the next spec release.

Here are some of the proposals:
#26 
#22 
#12 
#11 
#7 
#6 
#9 

Adding all to the discussion: @pterolex, @asholok, @maktwin, @SDSWanderer, @Prots, @WebbyLab, @YanaSavchenko, @antonfin, @siavolt

**Comment by Prots** [comment]
Maybe we can add [#25](https://github.com/koorchik/LIVR/issues/25) to this list?

**Comment by koorchik** [comment]
Not sure about #25. It is very rare case. I guess that any implementation can have it as additional rules. Or someone can create something like "livr-extra-rules" package where he can add as many rules as he wants. It has been a large delay but spec LIVR 0.5 (the version will be 2.0) is almost ready

**Comment by koorchik** [comment]
Additional case to test suite - https://github.com/koorchik/js-validator-livr/issues/11

**Comment by koorchik** [comment]
Done. The spec updated. JavaScript implementation already support all new features and passes all the tests.
