### ISSUE TITLE
Undefined behavior for empty lists in the list_xx rules

### ISSUE THREAD

**Issue by amakhrov** [koorchik/LIVR#29]
LIVR defines a couple of 'list' rules: list_of, list_of_objects, list_of_different_objects.
However, there is no test case for the situations when in the input data the list is empty ([]).
Most of the implementations treat it consistently - they consider [] to be a valid value.
However, the PHP implementation generates FORMAT_ERROR error in this case (only list_of and list_of_objects rules).

This happens because the test suit doesn't explicitly cover such cases.

The related PR: #28

**Comment by koorchik** [comment]
In master
