### ISSUE TITLE
Кода ошибки часто недостаточно для отображения ошибки

### ISSUE THREAD

**Issue by EviGL** [koorchik/LIVR#31]
Например, приходит ошибка TOO_LONG, для неё бы отобразить "Слишком длинное значение: значение должно быть не длиннее N символов", а этот самый N взять неоткуда.
К этому нужен какой-то интерфейс как получить соответствующее ошибке правило. Или возможность получить ошибки валидации в паре с правилами, тогда можно было бы прогнать какой-то цикл типа (псевдокод):
```
var errors = validator.getDetailedErrors();
foreach(error : errors){
   switch(error.code) {
      case "TOO_LONG": print("Слишком длинное значение: значение должно быть не длиннее "+
         error.rule.max_length +" символов")
   }
}
```

Можно, конечно, хардкодить тексты ошибок в местах реализации, мол, написали правило 
phone: {max_length: 10},
написали и сообщение об ошибке "телефон не может быть длиннее 10 символов"
Но тут проблемы:
1. Это приводит к дублированию значений в нескольких местах. Потом правило меняется, сообщение становится неактуальным, его забывают обновить, получается ошибка говорит "поле не длиннее 10 символов", а на самом деле оно должно быть не длиннее 8 уже.
2. Т.к. не для всех полей может быть задано специфичное сообщение, хотелось бы реализовать нормальное дефолтное: показать пользователю TOO_LONG это вообще плохо, а вот показать адекватное общее значение было бы норм ("поле дожно быть не длиннее 15 символов").

**Comment by EviGL** [comment]
Sorry, it's copy of #30

**Comment by koorchik** [comment]
Пока не часть спеки, но можно легко сделать так https://github.com/koorchik/js-validator-livr/pull/7#issuecomment-122299180
