### ISSUE TITLE
Equal to field not required allow

### ISSUE THREAD

**Issue by a-melnichuk** [koorchik/LIVR#32]
**Income**: 
- 2 not required fields must be equal 

**Desired outcome**:
- Not equal error for empty second field
- Equal for both empty or both field and equal

**Actual outcome**:
- Allow to live second field empty and validator return fields values

**Comment by koorchik** [comment]
If you say that the only second field (which is optional) should be equal to the first one. Then you should check in your code only the second field. Or you can set that first field should be always equal to the second one. [Here is an example](http://webbylab.github.io/livr-playground/#%7B%22rules%22%3A%22%7B%5Cn%20%20%20%20password%3A%20%7B%20equal_to_field%3A%20'password2'%20%7D%2C%5Cn%20%20%20%20password2%3A%20%7B%20equal_to_field%3A%20'password'%20%7D%5Cn%7D%22%2C%22data%22%3A%22%7B%5Cn%20%20%20%20password%3A%20''%2C%5Cn%20%20%20%20password2%3A%20''%5Cn%7D%22%7D)

Please, let me know if this does not solve the issue
