### ISSUE TITLE
Allows numbers which begin with 0 for integer

### ISSUE THREAD

**Issue by artemT82** [koorchik/LIVR#33]
http://webbylab.github.io/livr-playground/#%7B%22rules%22%3A%22%7B%5Cn%20%20%20%20age%3A%20integer%5Cn%7D%22%2C%22data%22%3A%22%7B%5Cn%20%20%20%20age%3A%20'04'%5Cn%7D%22%7D

Expected result: throws exception 'NOT_INTEGER"

**Comment by koorchik** [comment]
Fill be covered by test suite in LIVR 2.0 (coming soon)

**Comment by koorchik** [comment]
Fixed
