### ISSUE TITLE
"WRONG_DATE" is not a good error message.

### ISSUE THREAD

**Issue by Sandvich** [koorchik/LIVR#35]
I'm using LIVR for validation of user data. Said users are not necessarily tech-savvy, and to them this error would potentially imply that the date they have entered is incorrect, not that it isn't a date/can't be formatted as a date.
A few suggestions that me and my colleague have come up with:
- "NOT_A_DATE"
- "WRONG_FORMAT"
- "WRONG_DATE_FORMAT"

**Comment by SDSWanderer** [comment]
Error codes is not a user messages! 
You should probably map them into user-readable, (localized?), application-specific custom strings.

**Comment by Sandvich** [comment]
That's a fair enough thing to say, but the fact remains that the error message is saying something different to what the error actually is. Wrong date means that the data is wrong, not that it is in the wrong format. This was the main issue.

**Comment by koorchik** [comment]
Yes, WRONG_DATE is a little bit ambiguous. But I'd prefer to leave it as is to not harm existing projects as it will break backwards compatibility. The easiest solution for your case is to redefine the error with alias or custom rule. It is just several lines of code.

**Comment by koorchik** [comment]
Moreover, it is not clear what is "wrong date" then, I mean is feb 30 wrong date or wrong format? Currently, we just have single error code for the rule, maybe in future versions of the spec we will introduce additional error codes for the date related rules (but firstly we should move to semver)

**Comment by koorchik** [comment]
I close the issue, but will keep in mind the problem :)
