### ISSUE TITLE
Java implementation

### ISSUE THREAD

**Issue by jeedo** [koorchik/LIVR#38]
Needs a Java implementation ideally that could easily plug into [Spring](https://docs.spring.io/spring/docs/current/spring-framework-reference/html/validation.html)

**Comment by koorchik** [comment]
Sure, feel free to implement it. The main requirement for the implementation is to pass all the tests https://github.com/koorchik/LIVR/tree/master/test_suite. The easiest way is to take any implementation and to port it Java. I will be happy to help with any details of Perl and JS implementation (as I am the author). I believe that authors of other implementations are ready to help too.
