### ISSUE TITLE
not_empty_list behavior 

### ISSUE THREAD

**Issue by imatveev** [koorchik/LIVR#39]
Currently rule **not_empty_list** behaves as **required** rule and not contains `if ( util.isNoValue(value) ) return;` line. Is this an expected behavior? 
BTW: it concerns all implementations.

**Comment by koorchik** [comment]
Agree, it looks a little bit odd. The idea is that "not_empty_list" is like required/not_empty but in terms of list (the rule from the same category). Usually, if you want to allow empty list but the list is required, you just do something like [this](http://webbylab.github.io/livr-playground/#%7B%22rules%22%3A%22%7B%5Cn%20%20%20%20order_id%3A%20%5B'required'%2C%20'positive_integer'%5D%2C%5Cn%20%20%20%20products%3A%20%5B%20'required'%2C%20%7B%20'list_of_objects'%3A%20%7B%5Cn%20%20%20%20%20%20%20%20product_id%3A%20%5B'required'%2C'positive_integer'%5D%2C%5Cn%20%20%20%20%20%20%20%20quantity%3A%20%5B'required'%2C%20'positive_integer'%5D%5Cn%20%20%20%20%7D%7D%5D%5Cn%7D%22%2C%22data%22%3A%22%7B%5Cn%20%20%20%20order_id%3A%2010345%2C%5Cn%20%20%20%20products%3A%20%5B%5D%5Cn%7D%22%7D)
Does it make sense?

**Comment by imatveev** [comment]
And if you want to have non-required non-empty list? Best solution is custom rule?

**Comment by koorchik** [comment]
The simple workaround is to use or. [Here is the solution](http://webbylab.github.io/livr-playground/#%7B%22rules%22%3A%22%7B%5Cn%20%20%20%20order_id%3A%20%5B'required'%2C%20'positive_integer'%5D%2C%5Cn%20%20%20%20product_ids%3A%20%5B%20%7B%20or%3A%20%5B'not_empty_list'%5D%20%7D%2C%20%7B%5Cn%20%20%20%20%20%20%20'list_of'%3A%20%5B%20'required'%2C%20%20'positive_integer'%20%5D%5Cn%20%20%20%20%7D%5D%5Cn%7D%22%2C%22data%22%3A%22%7B%5Cn%20%20%20%20order_id%3A%2010455%2C%5Cn%20%20%20%20product_ids%3A%20%5B3566%5D%5Cn%7D%22%7D)

You can  use it directly or you can register it as an alias for { or: ['not_empty_list'] }
