### ISSUE TITLE
Add new Erlang validator

### ISSUE THREAD

**Issue by kostyushkin** [koorchik/LIVR#42]
It is likely that the olifer (Erlang validator) will no longer be supported because the developer has changed the stack. I completely rewrote it: https://github.com/erlangbureau/oliver
Can you add it to docs and playground?

**Comment by koorchik** [comment]
Yes, sure. I will add it. It is absolutely ok to have several implementations for the same language. 

Both implementations have the same name. Is it the one more implementation or is it a replacement for the older implementation from @Prots?

Moreover, as I see, @Prots responds quickly to the requests. Are you sure that it is not supported?

**Comment by kostyushkin** [comment]
Not the same, Oliver vs Olifer. Oliver developed as a replacement for the Olifer, but I completely rewrite code, so I give the new name to it.

I know @Prots, he switched to 'Go', maybe he will support the project for a while, but probably not for long. In any case, it's his business, if there is an opportunity to add another implementation, add pliz.

**Comment by koorchik** [comment]
Oh, I see. Great!  We are going to have a large update of the livr-spec.org soon, I will add Oliver too

**Comment by Prots** [comment]
@kostyushkin why have you decided that I don't support olifer? It smells bad... 
All critical bugs I fix and close ASAP any suggestion and PRs about improvement are welcome.
Some stuff like "rewrite it with using maps" is ok but try to do it via PRs. 

And it is bad idea to use very similar names to both implementation. Is it possible to rename new lib and avoid mess?

**Comment by kostyushkin** [comment]
@Prots Bro, I didn't want to offend you. It's your business continue development or not, but guys know that you change stack and asked me to add maps to olifer. I tried, but then I completely rewrite it.

**Comment by koorchik** [comment]
I agree with @Prots it is very easy to be confused with the names. You see, that I missed that the names are different. Different name for Oliver definitely a good idea

**Comment by kostyushkin** [comment]
Well, I will change the name, but I need time to come up with a new one.

**Comment by Prots** [comment]
**liver** is most suitable for it =)

**Comment by kostyushkin** [comment]
Yes, that's exactly what I came to.

**Comment by kostyushkin** [comment]
I have changed the name of the repository on GitHub and also I will change the names of the modules at the next commit today.

**Comment by kostyushkin** [comment]
Renamed. Added tests. Last 5 rules and will go into production.

**Comment by koorchik** [comment]
Done! Just added the implementation to http://livr-spec.org/ (the new site is in progress, but it is available now).
As for the LIVR multi playground, I've asked authors to add the new implementation.

**Comment by kostyushkin** [comment]
Thanks!

**Comment by koorchik** [comment]
Just published an article about LIVR http://blog.webbylab.com/language-independent-validation-rules-library/
