### ISSUE TITLE
Пропускает строку при "number_between"

### ISSUE THREAD

**Issue by YanaSavchenko** [koorchik/LIVR#5]
http://webbylab.github.io/livr-playground/#%7B%22rules%22%3A%22%7B%5Cnorder_id%3A%20%5B%20'required'%2C%20%7B'number_between'%3A%20%5B600%2C%2018000%5D%7D%20%5D%5Cn%7D%22%2C%22data%22%3A%22%7B%5Cn%20order_id%3A%20'forever'%5Cn%7D%22%7D

**Comment by SDSWanderer** [comment]
Так и должно быть. Добавь правило "decimal".

**Comment by koorchik** [comment]
@SDSWanderer конечно, в 90% нас интересует целое число и нужно добавлять integer, но в  логично запретить буквы в числах. number_between говорит что это должно быть число и никак не строка

**Comment by SDSWanderer** [comment]
@koorchik а не будет ли в таком случае потеряна целостность? Например правило "not_empty" не пропускает undefined и пустые строки, но нормально воспринимает объекты и массивы (в том числе пустые), т.е значения с "не правильным" типом позволены. Если изменить поведение "number_between" так, чтобы оно проверяло является ли значение числом, оно также как и буквы, не должно будет пропускать массивы и объекты. 
PS: Пока писал вспомнил что строковые правила проверяют тип, так что все-таки нужно сделать и тут такую проверку, если не число (или строка, выглядящая как число?) - FORMAT_ERROR.

**Comment by koorchik** [comment]
Пофикшено в свежей версии спеки и добавлены тесты в test suite.
