### ISSUE TITLE
Complex Domain Model

### ISSUE THREAD

**Issue by Vad1mo** [koorchik/LIVR#51]
Hello, 
very interesting project, and concept. 

We are thinking about creating a validation language to validate invoices 
(https://github.com/konik-io/konik).  

- Deep nested Data Structures or trees
- A rules can depend on multiple fields somewhere else in the tree.
- Rule should be able do do mathematical calculations.

I was wondering if this could be accomplished with LIVR? Are they any other similar projects?

**Comment by koorchik** [comment]
Hi @Vad1mo,
* You can validate deep data structures.
* Rules can depend on multiple fields somewhere else in the tree. You will get all siblings as the second parameter, but for accessing parents you will need some hacks (or a decorator for the validator). 
* You can do mathematical calculations.

If you have an axample of data and requirements for the validation, I will try to give you an example of how to do this in LIVR.
