### ISSUE TITLE
Validate keys in objects

### ISSUE THREAD

**Issue by chtseac** [koorchik/LIVR#56]
Is there a way to validate keys in an object?

To put it into a theorycraft example, something like this, borrowing `to_entries` and `from_entries` from [jq's filters of the same name](https://stedolan.github.io/jq/manual/v1.5/#to_entries,from_entries,with_entries):

Rule:

```
{
  author: ['required', 'string'],
  commits: ['to_entries', {
    'nested_object': {
      'key': ['required', {'like': '^[0-9a-f]+$'}],
      'value': ['required', 'string']
    }
  }, 'from_entries']
}
```

Valid data:

```
{
  author: 'chtseac',
  commits: {
    '6d12ba9': 'Add foo to bar',
    'e32d134': 'Initial commit'
  }
}
```

**Comment by koorchik** [comment]
Looking at your use case, I believe that there can be 3 possible options:
1. You can register several universal rules (like "object_keys", "object_values") for  validation.

```
{
  author: ['required', 'string'],
  commits: [
     'required',
     {'object_keys': [{ like: '^[0-9a-f]+$' }]
     {'object_values': ['required', {max_length: 10}]
   ], 
}
```
2. You can register a use case specific rule like 'commits_objects' or 'commits'
So, it will be 
```
{
  author: ['required', 'string'],
  commits: ['required', 'commits']
}
```
3. Change data format to commits: ```[ {hash: '6d12ba9', message: 'Add foo to bar', date: ...}, ...]```.
