### ISSUE TITLE
Добавить правило для сравнения поля с конкретным значением ( { 'equal' : 'value' } )

### ISSUE THREAD

**Issue by YanaSavchenko** [koorchik/LIVR#6]

**Comment by koorchik** [comment]
скорее правило будет называться eq:
```
 field: { eq : 'value' }
```

**Comment by SDSWanderer** [comment]
Можно обойтись 
```
field: { one_of: ['value'] }
```
Но отдельное правило не помешает, особенно для assert'ов в PHP-шних тестах

**Comment by koorchik** [comment]
Да, это первый вариант, который приходит на ум. Тут вопрос, очевидно ли это и типа для большей наглядности может добавить "eq"? @YanaSavchenko , @SDSWanderer , @pterolex  что думаете по этому поводу?

**Comment by koorchik** [comment]
В целом можно писать даже

```
field: {one_of: 'value'}
```

Возможно только eq лучше читается:
```
field: {eq: 'value'}
```

**Comment by koorchik** [comment]
Done.
