### ISSUE TITLE
Правило для любых обьектов (хешей)

### ISSUE THREAD

**Issue by SDSWanderer** [koorchik/LIVR#7]
Часто нет возможности описать все возможные ключи объекта с пошью правила ```nested_object```, тем не менее нужно проверить что пришел именно объект. Нужно добавить правило которое пропускает объект с любыми ключами. Было бы не плохо чтобы оно поддерживало ограничение на размер\длину\количество полей или вес объекта в целом, так как проверить поле с помошью ```max_length``` после ужесточения проверок типов уже нельзя, выдаст ```FORMAT_ERROR```.

**Comment by koorchik** [comment]
То есть, идея в том, чтобы добавить правила типа "any_object" ?

**Comment by SDSWanderer** [comment]
Часто нужно для сложных секций конфига, которые после валидации передаются как опции для какой-нибудь другой либы. Например, https://github.com/bergie/passport-saml. Очень много параметров, которые нет особо смысла описывать.
Другой случай - с клиента приходят настройки отображения некого виджета. Сервер ничего не знает про эти виджеты, он просто хранит пришедшие настройки в бд как сериализированную строку.

Пример правила:
```javascript
{any_object: {
    max_fileds_count: 20, 
    max_key_length: 20,
    max_value_length: 20, 
    max_nesting_level: 1, 
    max_total_size: 1024}
}
```

Не уверен что нужно именно в таком виде, мне лично хватило бы `max_total_size`.

**Comment by koorchik** [comment]
Слишком сложно получается. Думаю можно начать просто с "any_object" без параметров (в LIVR 0.5). А "max_total_size" просто сверить после валидации LIVR-ом при помощи каких-то других библиотек языка.

**Comment by koorchik** [comment]
Added "any_object" to the spec. Will be available when updated spec is published.
